// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qthuuijgmhstzfefzzpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aHV1aWpnbWhzdHpmZWZ6enBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDY1MjksImV4cCI6MjA2MjAyMjUyOX0.d3YMiPJKfnSAb7W9enI7TBE0Qs5ETAQl4ATKt5ddLxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);